server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.0.147:30001/breed?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.0.175:3306/breed?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root